#!/usr/bin/ruby
$LOAD_PATH << File.expand_path(File.dirname(__FILE__))+"/lib"
require 'dbblobcache'

#Daemonize
exit if fork                   # Parent exits, child continues.
Process.setsid                 # Become session leader.
exit if fork                   # Zap session leader. See [1].
#Dir.chdir "/"                  # Release old working directory.
File.umask 0000                # Ensure sensible umask. Adjust as needed.
#STDIN.reopen "/dev/null"       # Free file descriptors and
#STDOUT.reopen "/dev/null", "a" # point them somewhere sensible.
#STDERR.reopen STDOUT           # STDOUT/ERR should better go to a logfile.


#Start server
server = DBBlobCache.new
DRb.start_service("druby://:8880", server)
DRb.thread.join

